export const SLOT_PLATFORM_CACHE = [
  {
    id: 21,
    name: "PG",
    code: "PG",
    status: "OPEN",
    walletType: "SEAMLESS",
    gameType: "SLOT",
    followType: "FOLLOW",
    underMaintenance: false,
    maintenanceStartTime: null,
    maintenanceEndTime: null,
    alias: null,
    sequence: 1,
    title_vn: "PG Slots",
    title_en: "PG Slot",
    icon: "slot"
  },
  {
    id: 26,
    name: "XIN",
    code: "AG",
    status: "OPEN",
    walletType: "SEAMLESS",
    gameType: "LIVE,SLOT",
    followType: "NEW",
    underMaintenance: false,
    maintenanceStartTime: null,
    maintenanceEndTime: null,
    alias: null,
    sequence: 1,
    title_vn: "XIN Slots",
    title_en: "XIN Slot",
    icon: "slot"
  },
  {
    id: 8,
    name: "Jili",
    code: "JILI",
    status: "OPEN",
    walletType: "SEAMLESS",
    gameType: "FISH,SLOT",
    followType: "NEW",
    underMaintenance: true,
    maintenanceStartTime: "2024-08-06 08:00:00",
    maintenanceEndTime: "2024-08-06 11:00:00",
    alias: null,
    sequence: 2,
    title_vn: "Jili Slots",
    title_en: "Jili Slot",
    icon: "slot"
  },
  {
    id: 22,
    name: "PP",
    code: "PP",
    status: "OPEN",
    walletType: "SEAMLESS",
    gameType: "SLOT",
    followType: "FOLLOW",
    underMaintenance: false,
    maintenanceStartTime: null,
    maintenanceEndTime: null,
    alias: null,
    sequence: 3,
    title_vn: "PP Slots",
    title_en: "PP Slot",
    icon: "slot"
  },
  {
    id: 73,
    name: "MGP",
    code: "MGP",
    status: "OPEN",
    walletType: "SEAMLESS",
    gameType: "SLOT",
    followType: "FOLLOW",
    underMaintenance: false,
    maintenanceStartTime: null,
    maintenanceEndTime: null,
    alias: null,
    sequence: 4,
    title_vn: "MGP Slots",
    title_en: "MGP Slot",
    icon: "slot"
  },
  {
    id: 35,
    name: "Rich88",
    code: "RICH88",
    status: "OPEN",
    walletType: "SEAMLESS",
    gameType: "SLOT,POKER",
    followType: "NEW",
    underMaintenance: false,
    maintenanceStartTime: null,
    maintenanceEndTime: null,
    alias: null,
    sequence: 5,
    title_vn: "Rich88 Slots",
    title_en: "Rich88 Slot",
    icon: "slot"
  },
  {
    id: 30,
    name: "GPI",
    code: "GPI",
    status: "OPEN",
    walletType: "SEAMLESS",
    gameType: "SLOT,LOTTERY",
    followType: "NEW",
    underMaintenance: false,
    maintenanceStartTime: null,
    maintenanceEndTime: null,
    alias: null,
    sequence: 6,
    title_vn: "GPI Slots",
    title_en: "GPI Slot",
    icon: "slot"
  },
  {
    id: 33,
    name: "CQ9",
    code: "CQ9",
    status: "OPEN",
    walletType: "SEAMLESS",
    gameType: "SLOT",
    followType: "FOLLOW",
    underMaintenance: false,
    maintenanceStartTime: null,
    maintenanceEndTime: null,
    alias: null,
    sequence: 7,
    title_vn: "CQ9 Slots",
    title_en: "CQ9 Slot",
    icon: "slot"
  },
  {
    id: 17,
    name: "Habanero",
    code: "Habanero",
    status: "OPEN",
    walletType: "SEAMLESS",
    gameType: "SLOT",
    followType: "FOLLOW",
    underMaintenance: false,
    maintenanceStartTime: null,
    maintenanceEndTime: null,
    alias: null,
    sequence: 8,
    title_vn: "Habanero Slots",
    title_en: "Habanero Slot",
    icon: "slot"
  }
];
