export const ResponseCode = {
  SUCCESS: 0,
  ERROR_SYSTEM: 500,
  TOO_OFTEN_REQUEST: 504,
  ERROR_BAD_REQUEST: 400,
  ERROR_UNAUTHORIZED: 401,
  ERROR_FORBIDDEN: 403,
  ERROR_NOT_FOUND: 404,
  ERROR_METHOD_NOT_SUPPORT: 405,
  ERROR_LOGIN_INVALID_SESSION: 501,
  ERROR_LOGIN_EXPIRED_SESSION: 502,
  ERROR_PASS_REPEAT: 600,
  ERROR_NAME_EXIST: 601,
  ERROR_TOKEN_EXPIRED: 602,
  ERROR_TOKEN_MISSED: 603,
  ERROR_TOKEN_LOGGED: 604,
  ERROR_AMOUNT_DEPOSIT: 11003,
  ERROR_AMOUNT_PRIVILEGE_DEPOSIT: 11004,
  ERROR_WITHDRAW_PASSWORD_NOT_MATCH: 12100
};

const skipCode = [11002];

export function SkipErrorCode(code) {
  for (let i = 0; i < skipCode.length; i++) {
    if (skipCode[i] === code) {
      return 1;
    }
  }
  return 0;
}
